// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ke-the-coder

//@version=5
indicator("Day Trade Bar counting and EMAs", shorttitle="DT BC & EMA", overlay=true, max_labels_count=500)


var displayEveryBars = 3

is_new_day() =>
    d = dayofweek
    na(d[1]) or d != d[1]

var count = 1

count := is_new_day() ? 1 : count + 1 

if count == 1
    label_day = label.new(bar_index, 0, style=label.style_none, text=str.format("{0,time,d \n MMM}", time))
    label.set_yloc(label_day, yloc.belowbar)
    label.set_textcolor(label_day, #ffffffa9)
    label.set_size(label_day, size.normal)
else if count % displayEveryBars == 0
    label_bar = label.new(bar_index, 0, style=label.style_none, text=str.tostring(count))
    label.set_yloc(label_bar, yloc.belowbar)
    label.set_textcolor(label_bar, #4caf4fb9)
    label.set_size(label_bar, size.normal)
 

 
plot(ta.ema(close, 20), title="EMA", color=color.blue, offset=0)
// plot(na, title="EMA", color=#f1831c75, offset=0, linewidth=3)
plot(timeframe.in_seconds()/60 < 60 ? request.security(syminfo.tickerid, "60", ta.ema(close, 20), barmerge.gaps_on) : na, title="EMA", color=#f1831c75, offset=0, linewidth=2)
plot(timeframe.period != "D" ? request.security(syminfo.tickerid, "D", ta.ema(close, 20), barmerge.gaps_on) : na, title="EMA", color=#8b0e0ea3, offset=0, linewidth=3)

plot(timeframe.in_seconds()/60 >= 60 and timeframe.period != "W" ? request.security(syminfo.tickerid, "W", ta.ema(close, 20), barmerge.gaps_on) : na, title="EMA", color=#652ccea3, offset=0, linewidth=3)