// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ke-the-coder

//@version=6
indicator('Day Trade Bar counting and EMAs', shorttitle = 'DT BC&EMA', overlay = true, max_labels_count = 500)


displayEveryBars = input.int(3, title = 'Display every N bars', minval = 1)

is_new_day() =>
    d = dayofweek
    na(d[1]) or d != d[1]

var count = 1

count := is_new_day() ? 1 : count + 1

if count == 1
    label_day = label.new(bar_index, 0, style = label.style_none, text = str.format('{0,time,d \n MMM}', time))
    label.set_yloc(label_day, yloc.belowbar)
    label.set_textcolor(label_day, #ffffffa9)
    label.set_size(label_day, size.small)
else if count % displayEveryBars == 0 
    label_bar = label.new(bar_index, 0, style = label.style_none, text = str.tostring(count))
    label.set_yloc(label_bar, yloc.belowbar)
    label.set_textcolor(label_bar, #4caf4fb9)
    label.set_size(label_bar, size.normal)


ema20 = ta.ema(close, 20)
ema20_1h = timeframe.in_seconds() / 60 < 60 ? request.security(syminfo.tickerid, '60', ema20, barmerge.gaps_on) : na
ema20_d_now = timeframe.period != 'D' ? request.security(syminfo.tickerid, 'D', ta.ema(close, 20), barmerge.gaps_off, barmerge.lookahead_on) : na
ema20_d_prev = timeframe.period != 'D' ? request.security(syminfo.tickerid, 'D', ta.ema(close, 20)[1], barmerge.gaps_off) : na
var int bars_in_prev_day = 78
if is_new_day() and count[1] > 1
    bars_in_prev_day := count[1]
t = math.min(float(count) / float(bars_in_prev_day), 1.0)
t_curve = (1 - math.cos(t * math.pi)) / 2
ema20_d = not na(ema20_d_prev) and not na(ema20_d_now) ? ema20_d_prev + (ema20_d_now - ema20_d_prev) * t_curve : ema20_d_now
ema20_w = timeframe.in_seconds() / 60 >= 60 and timeframe.period != 'W' ? request.security(syminfo.tickerid, 'W', ta.ema(close, 20), barmerge.gaps_on) : na
avgBarSize = ta.sma(high - low, 20)

plot(ema20, title = 'EMA 20', color = color.blue, offset = 0, display = display.pane)
// plot(na, title="EMA", color=#f1831c75, offset=0, linewidth=3)
plot(ema20_1h, title = 'EMA 20 (1H)', color = #f1831c75, offset = 0, linewidth = 2, display = display.pane)
plot(ema20_d, title = 'EMA 20 (D)', color = #8b0e0ea3, offset = 0, linewidth = 3, display = display.pane)
plot(ema20_w, title = 'EMA 20 (W)', color = #652ccea3, offset = 0, linewidth = 3, display = display.pane)

var label lbl_avg = na

if barstate.islast
    label.delete(lbl_avg)
    lbl_avg := label.new(bar_index, low - avgBarSize * 5, text = 'Avg Bar  ' + str.tostring(avgBarSize, format.mintick), style = label.style_label_up, color = #555555, textcolor = color.white, size = size.small)
